id: e85aaef3-20fd-4cf9-b255-e9cf895d4066
name: start-minecraft
description: Start a Minecraft server by VM name
inputs:
  properties:
    vmName:
      type: string
      description: VM name to start
    tmuxSession:
      type: string
      description: Tmux session name for the Minecraft server
    serverDir:
      type: string
      description: Server directory path
    startScript:
      type: string
      description: Start script path
    logPath:
      type: string
      description: Server log path
  required:
    - vmName
    - tmuxSession
    - serverDir
    - startScript
    - logPath
jobs:
  - name: main
    description: Auth, start VM via fleet, then start Minecraft server
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: ensure-vm-running
        description: Start VM if stopped and wait for IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: start
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: start-minecraft
        description: Start Minecraft server and wait for ready
        task:
          type: model_method
          modelIdOrName: minecraftGame
          methodName: startMinecraftServer
        dependsOn:
          - step: ensure-vm-running
            condition:
              type: succeeded
        weight: 0
      - name: annotate
        description: Create Grafana annotation
        task:
          type: model_method
          modelIdOrName: grafanaHub
          methodName: createAnnotation
          inputs:
            tags: '["game", "start", "${{ inputs.vmName }}"]'
            text: '${{ inputs.vmName }} started'
        dependsOn:
          - step: start-minecraft
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
