id: 4e11e3ef-8854-4d31-a980-fd572f97c3e0
name: stop-minecraft
description: Stop a Minecraft server by VM name
inputs:
  properties:
    vmName:
      type: string
      description: VM name to stop
    tmuxSession:
      type: string
      description: Tmux session name for the Minecraft server
    serverDir:
      type: string
      description: Server directory path
    startScript:
      type: string
      description: Start script path
    logPath:
      type: string
      description: Server log path
  required:
    - vmName
    - tmuxSession
    - serverDir
    - startScript
    - logPath
jobs:
  - name: main
    description: Auth, look up VM via fleet, warn players, stop Minecraft, stop VM
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: lookup
        description: Find VM by name and populate vmid/IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: warn-players
        description: Broadcast shutdown warning to Minecraft players
        task:
          type: model_method
          modelIdOrName: minecraftGame
          methodName: warnShutdown
        dependsOn:
          - step: lookup
            condition:
              type: succeeded
        weight: 0
      - name: stop-minecraft
        description: Gracefully stop Minecraft server process
        task:
          type: model_method
          modelIdOrName: minecraftGame
          methodName: stopMinecraftServer
        dependsOn:
          - step: warn-players
            condition:
              type: succeeded
        weight: 0
      - name: stop-vm
        description: Shut down the VM
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: stop
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: stop-minecraft
            condition:
              type: succeeded
        weight: 0
      - name: annotate
        description: Create Grafana annotation
        task:
          type: model_method
          modelIdOrName: grafanaHub
          methodName: createAnnotation
          inputs:
            tags: '["game", "stop", "${{ inputs.vmName }}"]'
            text: '${{ inputs.vmName }} stopped'
        dependsOn:
          - step: stop-vm
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
