id: 7469bfde-1b52-4b7f-a3a5-1aa8200077f0
name: minecraft-install
description: Install and start a Minecraft server from a server pack zip on any VM
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to install on
  serverPackPath:
    type: string
    required: true
    description: Local path to the server pack zip file
  serverDir:
    type: string
    required: false
    default: ~/game
    description: Remote directory for the server
  jvmMemory:
    type: string
    required: false
    default: 10G
    description: JVM memory allocation
jobs:
  - name: main
    description: Install deps, upload pack, extract, configure, start server
    steps:
      - name: auth
        description: Authenticate with Proxmox
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: lookup-vm
        description: Lookup target VM to populate fleet resource
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: install-deps
        description: Install JDK, tmux, bash, curl, unzip on the VM
        task:
          type: model_method
          modelIdOrName: minecraftInstaller
          methodName: installDeps
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
        weight: 0
      - name: upload-pack
        description: Upload server pack zip to the VM
        task:
          type: model_method
          modelIdOrName: minecraftInstaller
          methodName: upload
          inputs:
            vmName: '${{ inputs.vmName }}'
            serverPackPath: '${{ inputs.serverPackPath }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
        weight: 0
      - name: extract-pack
        description: Extract server pack and discover modloader config
        task:
          type: model_method
          modelIdOrName: minecraftInstaller
          methodName: extract
          inputs:
            vmName: '${{ inputs.vmName }}'
            serverDir: '${{ inputs.serverDir }}'
        dependsOn:
          - step: install-deps
            condition:
              type: succeeded
          - step: upload-pack
            condition:
              type: succeeded
        weight: 0
      - name: configure-server
        description: Configure JVM memory, EULA, and server variables
        task:
          type: model_method
          modelIdOrName: minecraftInstaller
          methodName: configure
          inputs:
            vmName: '${{ inputs.vmName }}'
            jvmMemory: '${{ inputs.jvmMemory }}'
        dependsOn:
          - step: extract-pack
            condition:
              type: succeeded
        weight: 0
      - name: start-server
        description: Start the Minecraft server in a tmux session
        task:
          type: model_method
          modelIdOrName: minecraftGame
          methodName: startMinecraftServer
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: configure-server
            condition:
              type: succeeded
        weight: 0
      - name: enable-monitoring
        description: Enable node-exporter textfile collector for metrics
        task:
          type: model_method
          modelIdOrName: monitoringAgent
          methodName: enableTextfileCollector
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: start-server
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
